[workspace]

members = [
    "foxbot",
    "foxbot-sites",
    "foxbot-models",
    "foxbot-utils",
    "foxbot-channel-worker"
]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true
codegen-units = 1
