FROM rust:1.50-slim-buster AS builder
WORKDIR /src
COPY ./foxbot-channel-worker/foxbot-channel-worker ./foxbot-channel-worker
RUN strip ./foxbot-channel-worker

FROM registry.huefox.com/foxbot-base
COPY ./langs ./langs
COPY --from=builder /src/foxbot-channel-worker /bin/foxbot-channel-worker
CMD ["/bin/foxbot-channel-worker"]
