[package]
name = "foxbot-models"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
prometheus = "0.12"

lazy_static = "1"

serde = "1"
serde_json = "1"

sqlx = { version = "0.5", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "offline", "json", "migrate", "time"] }

tgbotapi = { git = "https://github.com/Syfaro/tgbotapi-rs" }
