name: Release

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            target/
          key: ${{ runner.os }}-release-${{ hashFiles('Cargo.lock') }}

      - name: Get stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Move binaries
        run: |
          mv target/release/foxbot foxbot/foxbot
          mv target/release/foxbot-background-worker foxbot-background-worker/foxbot-background-worker
          mv target/release/foxbot-discord foxbot-discord/foxbot-discord

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            foxbot/foxbot
            foxbot-background-worker/foxbot-background-worker
            foxbot-discord/foxbot-discord

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract FoxBot metadata for Docker
        id: meta-foxbot
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/foxbot

      - name: Extract FoxBot Background Worker metadata for Docker
        id: meta-foxbot-background-worker
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/foxbot-background-worker

      - name: Extract FoxBot Discord metadata for Docker
        id: meta-foxbot-discord
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/syfaro/foxbot-discord

      - name: Build and push FoxBot Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta-foxbot.outputs.tags }}
          labels: ${{ steps.meta-foxbot.outputs.labels }}
          file: foxbot/Dockerfile

      - name: Build and push FoxBot Background Worker Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta-foxbot-background-worker.outputs.tags }}
          labels: ${{ steps.meta-foxbot-background-worker.outputs.labels }}
          file: foxbot-background-worker/Dockerfile

      - name: Build and push FoxBot Discord Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta-foxbot-discord.outputs.tags }}
          labels: ${{ steps.meta-foxbot-discord.outputs.labels }}
          file: foxbot-discord/Dockerfile
